### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by zkeyword** [PackageBox/webpack-avalon2-seed#1]
> webpack-avalon2-seed@1.0.0 dev E:\personal\webpack-avalon2-seed
> NODE_ENV=development webpack-dev-server --hot --inline --devtool eval --progre
ss --colors --content-base dist_tests

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jianxin.zhu\\App
Data\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.0.0
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! webpack-avalon2-seed@1.0.0 dev: `NODE_ENV=development webpack-dev-serve
r --hot --inline --devtool eval --progress --colors --content-base dist_tests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-avalon2-seed@1.0.0 dev script 'NODE_ENV=developme
nt webpack-dev-server --hot --inline --devtool eval --progress --colors --conten
t-base dist_tests'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-avalon2-seed
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development webpack-dev-server --hot --inline --devtool ev
al --progress --colors --content-base dist_tests
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-avalon2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-avalon2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\personal\webpack-avalon2-seed\npm-debug.log

**Comment by VanquisherMe** [comment]
window：
SET NODE_ENV=development
webpack-dev-server --hot --inline --devtool eval --progress --colors --content-base dist_tests
以此类推

**Comment by zkeyword** [comment]
npm run dev 提示以上错误，环境node6

**Comment by VanquisherMe** [comment]
重新克隆下最新的 我测试过了 已经可以了 ，npm  install 要下载完整

**Comment by zkeyword** [comment]
已经OK了，请问是否有集成路由（spa）的方案？

**Comment by VanquisherMe** [comment]
暂时没有
可以参考下这个 https://github.com/PeopleStealth/avalon-webpack-spa

**Comment by zkeyword** [comment]
tks
