### ISSUE TITLE
想了解这个项目怎么跑起来？

### ISSUE THREAD

**Issue by henryzp** [PackageBox/webpack-avalon2-seed#4]
在做npm install之后

用npm run dev，但是访问`localhost:3000`结果不到结果

![image](https://cloud.githubusercontent.com/assets/3849702/17352321/540ce3da-5968-11e6-9478-7250a5829910.png)

**Comment by henryzp** [comment]
是不是有文件没有上传？

还是我访问的路径有问题，但我用`localhost:3000/app/_view/index.html`也是不行

另外想问问，这里包括了route的功能了吗？是属于spa的项目

**Comment by VanquisherMe** [comment]
这是一个 多页应用的搭建 没有route 
多页应用 一般在 node服务端做 route 
localhost:3000/_views 是在这个路径下
SPA可以参考
https://github.com/wandergis/avalon-webpack-spa

**Comment by henryzp** [comment]
@VanquisherMe ，但是多页应用的项目，怎么跑起来呢？

我上面的为什么不行？

**Comment by henryzp** [comment]
还有上面的spa，avalon用的是2.x版本吗？还是1.4的

**Comment by VanquisherMe** [comment]
那个不是 2.x 但是 部署 webpack route 的思路可以参考
localhost:3000/_views 是这个路劲
你可能不太理解 webpack 再缓存里的 root 目录 可以去看下 webpack 的文档

**Comment by henryzp** [comment]
@VanquisherMe ,thank you。。

但我觉得这个路径是不是也最好写到readme里面呢？我平常webpack用的不多，所以就不清楚了

**Comment by VanquisherMe** [comment]
根目录确实是 http://localhost:3000 静态页面在 _views目录下
![Uploading 50FA4959-66D3-41DB-B7B8-3F15F4644D40.png…]()
http://localhost:3000 ==./dist [root]
所以访问 必然是_views

**Comment by VanquisherMe** [comment]
根目录确实是 http://localhost:3000 静态页面在 _views目录下
这是打包后的文件
![50fa4959-66d3-41db-b7b8-3f15f4644d40](https://cloud.githubusercontent.com/assets/4927398/17358724/eb106cd4-5995-11e6-9889-9479b66a9504.png)
http://localhost:3000 ==./dist [root]
所以访问 必然是_views
